pipeline:
  name: GitEx-Pipeline1
  identifier: GitExPipeline1
  projectIdentifier: GitExProject
  orgIdentifier: CSE_Labs
  tags: {}
  stages:
    - stage:
        name: echoMe
        identifier: echoMe
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "Hello World from git"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
